name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Running Tests"

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: build
        run: echo "Running Build"
